### ISSUE TITLE
Scripture naming variations

### ISSUE THREAD

**Issue by Llewellynvdm** [sermonindex/audio_api#1]
I do see a number of mismatch on the scripture area... we may what to combine all those variations of each book. We can use the standard naming from the kjv @sermonindex-dev let me know what you think.

**Comment by sermonindex-dev** [comment]
Can you post an example of the variations?

**Comment by sermonindex-dev** [comment]
I see the problem, 

for 1 Kings:

1_king
1_kings
1kings

obviously this one "1_kings" is the highest used and right way logically I think. I used a space between references and chapters for almost all scripture references and otherwise they would be mistakes from my input side.

Is there a way to almagamate those smaller listings to the main one?  Also any short references. like 1 Cor.  should rather be 1 Corinthians.  (the full spelling for the bible book)

**Comment by Llewellynvdm** [comment]
Yes, I can do that, just wanted to make sure you will be okay with that, so I will push up the fix in a few hours.

**Comment by sermonindex-dev** [comment]
Perfect sounds good to me brother.
