### ISSUE TITLE
Incomplete list of speakers JSON?

### ISSUE THREAD

**Issue by sermonindex-dev** [sermonindex/audio_api#2]
It seems the list stops with "R" but others alphabetically onwards are not uploaded yet:

https://github.com/sermonindex/api/tree/master/speaker

**Comment by Llewellynvdm** [comment]
No that is only what it shows in the gitHub GUI, because they truncated it, here is the message:
![image](https://user-images.githubusercontent.com/5607939/50621565-4484f100-0f0f-11e9-9886-70d98df93c94.png)

So here you will see the full list:
https://github.com/sermonindex/api/blob/master/speaker/_sermonindex.json
or
http://www.sermonindex.net/api/speaker/_sermonindex.json

You can test the availability by trying to open any one of those in the list
http://www.sermonindex.net/api/speaker/zeb_mcdaris.json <-- is the last one
