### ISSUE TITLE
Can't find speaker sermons in API.

### ISSUE THREAD

**Issue by sherebiahtishbi** [sermonindex/audio_api#8]
@Llewellynvdm can you pls check? for some speaker api is just redirecting to sermonindex/audio_api page instead of giving JSON for that speaker. Found two so far as below
>>>>>>>>>> 
aa_allen.json
aj_gordon.json

**Comment by Llewellynvdm** [comment]
Okay so it seems those speakers do not have sermons in the database that I have. I will check again, but I see they are also not in the [first API](https://github.com/sermonindex/audio_api/tree/586029a5cd08ae8190fc8e11f920472037ecfe29/speaker), I must have added them by accident to the list of speakers.

I will check the script to prevent speakers from being added if they do not have audio sermons, they could only have video sermons on SermonIndex, since they are part of the speaker list. But this API is just audio, at this point.

**Comment by Llewellynvdm** [comment]
Okay I have removed the speakers that has no audio sermons in the database I have.

Brother @sermonindex-dev please go [over the list removed](https://github.com/sermonindex/audio_api/commit/9701f47235a46582fcc53b282f33109c8f07144e), and confirm that these do not have audio files currently.

Once confirmed, you will need to make a pull to update the live system again.

**Comment by sermonindex-dev** [comment]
@Llewellynvdm  that list of removed speakers due to no sermons looks correct.

**Comment by Llewellynvdm** [comment]
Okay so this issue is resolved.
